package day06;

import java.io.IOException;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.Arrays;
import day06.IOUtils.*;

public class ListClient {
    public static void main(String[] args) {

        // get arguments
        String numOfNums = args[0];
        String maxValue = args[1];
        String ipAddy = args[2];
        Integer port = Integer.parseInt(args[3]);

        try {
            // connect to server
            Socket socket = new Socket(ipAddy, port);
            System.out.printf("Connected to %s:%d\n", socket.getInetAddress(), socket.getPort());

            // write to server with n and limit
            IOUtils.write(socket, numOfNums + " " + maxValue);

            // read input stream
            String[] listOfRandNum = IOUtils.read(socket).split(",");
            System.out.print("Random numbers generated by server: ");
            System.out.println(Arrays.toString(listOfRandNum));

            // get average from the list of nums
            Float total = 0f;
            Integer i;
            for (i = 0; i < listOfRandNum.length; i++) {
                total += Integer.parseInt(listOfRandNum[i]);
            }
            System.out.printf("Average of random numbers is %.2f", total / i);

            socket.close();
            System.out.println("socket closed");

        } catch (UnknownHostException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
